version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  lint:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run lint
          command: make lint

  test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint